config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'
	get    'login'   => 'sessions#new'
	post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'

	resources :tasks, only: [:index, :edit, :create, :update, :destroy]

	resources :users, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
		resources :tasks, only: [:edit, :create, :update, :destroy]
	end
end

app/models/task.rb
class Task < ActiveRecord::Base
	attr_accessor :documents

	belongs_to :writer, class_name: 'User'
	belongs_to :peer_reviewer, class_name: 'User'

	validates :product,  presence: true
	validates :doc_type, inclusion: { in: %w(Datasheet Manual QIG), message: "must be a Datasheet, Manual, or QIG" }
	validates :status, inclusion: { in: %w(Queued In\ Progress Pending), message: "must be Queued, In Progress, or Pending" }
	validates :review_status, inclusion: { in: %w(Not\ Sent Sent Reviewed), message: "must be Not Sent or Sent, or Reviewed" }
	validate :writer_not_pr
	before_validation :default_values

	def name
		"#{self.product} #{self.revision} #{self.doc_type} #{self.version} (#{self.region})"
	end

	def writer
		return User.find_by(id: self.writer_id).name
	end

	def reviewer
		return User.find_by(id: self.reviewer_id).name
	end

	private
	def default_values
		self.status ||= "Queued"
		self.start_date ||= Date.today
		self.done ||= false
		self.review_status ||= "Not Sent"
		return true # To prevent a false return value!
	end

	def writer_not_pr
		errors.add(:reviewer_id, "should not be the writer") if (not self.writer_id.nil?) and self.reviewer_id == self.writer_id
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]
  before_action :admin_only, only: [:index]
  before_action :correct_owner, only: [:edit, :destroy]
  before_action :correct_owner_or_reviewer, only: [:update]

  # GET /users/1/tasks
  # GET /tasks.json
  def index
    @users = User.all
    @unassigned = Task.where(writer_id: nil)
    @task = Task.new
    session[:return_to] = request.fullpath
  end

  # GET /tasks/1/edit
  def edit
    session[:return_to] = request.referer
  end

  # POST /tasks
  # POST /tasks.json
  def create

    # Deal with no documents selected
    if params[:task][:documents].nil?
      flash.now[:alert] = "Please select at least one document type."
      @task = Task.new(task_params)
      flash.keep :user_created
      render 'shared/_new_form' and return
    end

    # Save each document type in a separate task
    params[:task][:documents].each do |doc_type|
      @task = Task.new(task_params)
      @task.doc_type = doc_type
      @task.writer_id ||= flash[:user_created]

      render 'shared/_new_form' and return unless @task.save
    end

    redirect_to session.delete(:return_to), notice: params[:task][:documents].length > 1 ? 'Tasks were successfully added.' : 'Task was successfully added.'
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to session.delete(:return_to), notice: 'Task was successfully updated.' }
        format.json { render :index, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Task was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:review_date, :review_sent_date, :review_status, :writer_id, :reviewer_id, :flow, :product, :doc_type, :start_date, :version, :revision, :status, :region, :done, :draft, :draft_submitted, :completion_date, :notes)
    end
  end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_error_messages.html.erb
<% if @task.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

  <ul>
    <% @task.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/tasks/_tasks_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= sort_link "Flow", "flow" %></th>
      <th><%= sort_link "Document", "product" %></th>
      <th><%= sort_link "Start Date", "start_date" %></th>
      <th><%= sort_link "Status", "status" %></th>

      <% if unassigned %>
        <th>Writer</th>
        <th>Reviewer</th>
        <th colspan="3"></th>
      <% else %>
        <th><%= sort_link "Latest Draft", "draft_submitted" %></th>
        <th>Peer Review</th>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr>
        <td><%= task.flow %></td>
        <td><%= task.name %></td>
        <td><%= task.start_date %></td>
        <td><%= task.status %></td>
        <% if unassigned %>
          <%= form_for task do |f| %>
            <td>        
              <%= f.select :writer_id, options_for_select({ "Unassigned" => nil }.merge(User.get_options_for_select), @task.writer_id), {}, {class: "form-control"} %>        
            </td>
            <td>
              <%= f.select :reviewer_id, options_for_select({ "None" => nil }.merge(User.get_options_for_select), @task.reviewer_id), {}, {class: "form-control"} %>
            </td>
            <td>
              <%= f.submit "Assign", { class: "btn btn-default" } %>
            </td>
          <% end %>
        <% else %>
          <td>
            <% if task.draft and task.draft_submitted %>
            <%= "Draft #{task.draft} (#{days_ago task.draft_submitted})" %>
            <% end %>
          </td>

          <td>
            <% if task.reviewer_id.nil? %>
              No peer reviewer
            <% elsif task.review_status == "Reviewed" %>
              <span class="glyphicon glyphicon-ok"></span>
              Peer reviewed by <strong><%= task.reviewer %></strong> <%= "(#{days_ago task.review_date})" %>
            <% elsif task.review_status == "Sent" %>
              Sent to <strong><%= task.reviewer %></strong> for PR <%= task.review_sent_date.nil? ? "" : "(#{days_ago task.review_sent_date})" %>
            <% else %>
              Not yet sent to <strong><%= task.reviewer %></strong>
            <% end %> 
          </td>
        <% end %>           
         
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for(@task) do |f| %>

<%= render 'error_messages' %>

<h3>Update Task Status</h3>


<div class="field form-group">
  <%= f.label :status, "Status" %>
  <%= f.select :status, options_for_select(%w(Queued In\ Progress Pending), @task.status), {}, {class: "form-control"} %>
</div>
<div class="field form-group">
  <%= f.label :draft, "Latest Draft" %>
  <%= f.number_field :draft, min: 1, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :draft_submitted, "Draft Submitted" %>
  <%= f.date_field :draft_submitted, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :notes, "Notes" %>
  <%= f.text_area :notes, class: "form-control" %>
</div>
<br>
<div class="field form-group">
  <%= f.label :review_status, "Peer Review Status" %>
  <%= f.select :review_status, options_for_select(%w(Not\ Sent Sent Reviewed), @task.review_status), {}, {class: "form-control"} %>
</div>
<div class="field form-group">
  <%= f.label :review_sent_date, "Peer Review Sent Date" %>
  <%= f.date_field :review_sent_date, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :review_date, "Peer Review Completion Date" %>
  <%= f.date_field :review_date, class: "form-control" %>
</div>
<br>
<div class="field form-group">
  <%= f.label :done do %>
  <%= f.check_box :done %>
  <span>Task Completed</span>
  <% end %>
</div>
<div class="field form-group">
  <%= f.label :completion_date, "Completion Date" %>
  <%= f.date_field :completion_date, class: "form-control" %>
</div>

<br>
<h3>Edit Task Details</h3>

<div class="field form-group">
  <%= f.label :writer_id, "Writer" %>
  <%= f.select :writer_id, options_for_select({ "Unassigned" => nil }.merge(User.get_options_for_select), @task.writer_id), {}, {class: "form-control"} %>
</div>

<div class="field form-group">
  <%= f.label :reviewer_id, "Peer Reviewer" %>
  <%= f.select :reviewer_id, options_for_select({ "None" => nil }.merge(User.get_options_for_select), @task.reviewer_id), {}, {class: "form-control"} %>
</div>

<div class="field form-group">
  <%= f.label :start_date, "Start Date" %>
  <%= f.date_field :start_date, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :flow, "Flow Number" %>
  <%= f.text_field :flow, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :product, "Model Number" %>
  <%= f.text_field :product, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :revision, "Hardware Revision" %>
  <%= f.text_field :revision, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :doc_type, "Document Type" %>
  <%= f.select :doc_type, options_for_select(%w(Datasheet QIG Manual), @task.doc_type), {}, {class: "form-control"} %>
</div>
<div class="field form-group">
  <%= f.label :version, "Document Version" %>
  <%= f.text_field :version, class: "form-control" %>
</div>
<div class="field form-group">
  <%= f.label :region %>
  <%= f.text_field :region, class: "form-control" %>
</div>

<div class="actions">
  <%= f.submit "Save Changes", class: "btn btn-primary" %>
</div>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks Admin</h1>

<h2>Unassigned</h2>
<%= render 'tasks_table', tasks: sort_tasks(@unassigned), unassigned: true %>

<div class="row">
  <div class="col-sm-3">    

    <%= render 'shared/new_form' %>

  </div>
</div>

<div style="margin-top: 50px;">
<% @users.each do |user| %>
<h2><%= user.name %></h2>

<%= render 'tasks_table', tasks: sort_tasks(user.tasks.where(done: false)), unassigned: false %>

<% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Flow:</strong>
  <%= @task.flow %>
</p>

<p>
  <strong>Product:</strong>
  <%= @task.product %>
</p>

<p>
  <strong>Doc type:</strong>
  <%= @task.doc_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Region:</strong>
  <%= @task.region %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @task.draft %>
</p>

<p>
  <strong>Draft submitted:</strong>
  <%= @task.draft_submitted %>
</p>

<p>
  <strong>Completion date:</strong>
  <%= @task.completion_date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @task.notes %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>