config/routes.rb
Rails.application.routes.draw do

	root 'sessions#new'
	get    'login'   => 'sessions#new'
	post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'

	resources :tasks, only: [:index, :edit, :create, :update, :destroy]

	resources :users, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
		resources :tasks, only: [:edit, :create, :update, :destroy]
	end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
	<div class="navbar-header">
			<%= link_to "Documentation Task Manager", root_url, class: "navbar-brand" %>
			</div>
<div id="navbar" class="navbar-collapse collapse">
			
			<ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
				<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Welcome <strong><%= current_user.name %> </strong><span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
				<% if logged_in? %>
				<li><%= link_to "Task List", current_user %></li>
					<li><%= link_to "Edit User Details", edit_user_path(current_user) %></li>
					<% if current_user.admin %>
					<li class="divider"></li>
						<li><%= link_to "Tasks Admin", tasks_path %></li>
						<li><%= link_to "Users Admin", users_path %></li>
					<% end %>
				<% end %>
			</ul>
				</li>
				<li><%= button_to "Log Out", logout_path, method: "delete", class: "btn btn-default navbar-btn" %></li>
				<% else %>
					<li><%= button_to "Sign Up", new_user_path, method: "get", class: "btn btn-default navbar-btn" %></li>
					<li><%= button_to "Log In", login_path, method: "get", class: "btn btn-default navbar-btn" %></li>
				<% end %>
			</ul>
			</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HqStatus</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	<%= render 'layouts/navbar' %>


			<p id="notice"><%= notice %></p>
			<p id="alert"><%= alert %></p>
			<%= yield %>
		<%= debug(params) if Rails.env.development? %>
	</div>

</body>
</html>